<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sentry" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
  </ItemGroup>

</Project>

