<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0-macos</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <UseAppHost>true</UseAppHost>
        <SelfContained>true</SelfContained>
        <EnableMacOSCodeSign>true</EnableMacOSCodeSign>
        <ApplicationId>com.leleji.ClipFlow</ApplicationId>
        <InfoPlistPath>Info.plist</InfoPlistPath>
        <CFBundleIconFile>logo.icns</CFBundleIconFile>
        <ApplicationIcon>..\ClipFlow.Desktop\Assets\logo.ico</ApplicationIcon>
        <SupportedOSPlatformVersion>10.15</SupportedOSPlatformVersion>
    </PropertyGroup>
    <ItemGroup>
        <BundleResource Include="..\ClipFlow.Desktop\Assets\logo.icns">
            <Link>logo.icns</Link>
        </BundleResource>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\ClipFlow.Core\ClipFlow.Core.csproj" />
    </ItemGroup>
</Project>
